### ISSUE TITLE
Windows Vista not supported (PSAPI version)

### ISSUE THREAD

**Issue by EliteOutcaster** [JamesWilko/Payday-2-BLT#10]
I am using Windows Vista. I downloaded the BLT, extracted both folders (Mods and IPHLPAPI.dll) into the Payday 2 Folder. I downloaded the vcredist_x64.exe and vcredist_x84.exe. When I open the game from Steam, I get the error," Engine has stopped working." When I open the game from the Payday 2 Folder, I get," The procedure entry point K32GetModuleInformation could not be located in the dynamic link library KERNEL32.dll, followed by Engine has stopped working. When I remove the IPHLPAPI.dll, the game works normally. (I do not have any other addons like Hoxhud) 

Okay I got a reply saying Vista doesn't work yet.

**Comment by SirWaddles** [comment]
Thanks for reporting this issue.
The call K32GetModuleInformation is only available in PSAPI version 2 and greater (Windows 7 and greater)
We are working on a fix, however it requires the disuse of C++11 features, which are core to multi-threading compatability.

**Comment by SirWaddles** [comment]
Re-opening (but renaming) issue.
This is a known issue that needs to be solved.

**Comment by thatguyfrombb** [comment]
Got it running. No changes needed to the code. I followed the MSDN documentation (https://msdn.microsoft.com/en-us/library/windows/desktop/ms683201%28v=vs.85%29.aspx). Define PSAPI_VERSION = 1 (In preprocessor definitions in the project settings) and including the library "psapi.lib".

![windows vista x64 edition-2015-06-04-05-30-54](https://cloud.githubusercontent.com/assets/11382298/7976439/3948e2f2-0a7b-11e5-9a61-aa60a9160f32.png)

**Comment by SirWaddles** [comment]
I kinda read that solution as a hotfix. Then again, BLT is already very hacky.

Make a PR and I'll merge, but I don't feel capable of committing the mortal sin of intentionally writing hacky code.

**Comment by GHBDougley** [comment]
Is there a compiled version of this available for download?

**Comment by SinZ163** [comment]
+1 on is there a compiled version available, I wasn't able to resolve the dependencies to get the project compiling

**Comment by jaw20** [comment]
SirWaddles. There is no modification to the code necessarily needed. You need to add Psapi.lib to the TARGETLIBS macro and compile the program with -DPSAPI_VERSION=1. There is no way we can add that in to your source code because it relates to compilation rather than the actual code.

**Comment by GHBDougley** [comment]
Any progress on this?  A team member of mine is stuck on vista and is still awaiting a compatibility fix.

**Comment by JamesWilko** [comment]
There are no plans to officially support anything except Windows 7, 8, and 10.
