### ISSUE TITLE
BLT don't working

### ISSUE THREAD

**Issue by TangoWhiskyFoxtrot** [JamesWilko/Payday-2-BLT#101]
Hello, i have a problem. When i unzip archive in game folder, BLT don't working. No Lua Mods, no Mod Options, nothing!

**Comment by WubTheGame** [comment]
Same issue here, i have all my mods, and the BLT file in my game directory.

**Comment by dive-bomber** [comment]
If you're on Windows 7, you need to wait till mister Wilko fixes it.

**Comment by WubTheGame** [comment]
I am. How long will that take?

**Comment by AkiraDaishiyuExe** [comment]
Depend on where is the problem and how it can be fix. It's variable. I think you can wait for a long moment, just play the vanilla version, it isn't good because you use your mods so much (like me) but that isn't bad at all. It's feel weird but it's still enjoyable ^^

**Comment by wilhelmIX** [comment]
Thanks for your answer, but did mr senpai James said anything about his work on fix?

**Comment by AkiraDaishiyuExe** [comment]
He is working on it but you know, it's kinda hard to find how BLT doesn't work on Win7 but you just have to be patient ^^

**Comment by WubTheGame** [comment]
but modz4Lyfe xD

But in all seriousness i'll try to wait and try to play vanilla.

**Comment by JamesWilko** [comment]
Most likely fixed in the BLT 2.1 update.

**Comment by Auscobe** [comment]
Yeah, it is. Thanks. =)
