### ISSUE TITLE
Are we required to download the mod manager now or something? 

### ISSUE THREAD

**Issue by roninsix** [JamesWilko/Payday-2-BLT#103]
I paste the latest download in payday folder and then launch game and I get this window popping up in the background that gives me a bunch of error messages and get no mod menu or options in game. 
![pd2](https://user-images.githubusercontent.com/31544425/29976419-8f8a358e-8eff-11e7-988a-a3af17993be4.jpg)

**Comment by BangL** [comment]
no, your broken/out-of-date mods are simply preventing the blt from working properly. maybe try starting clean instead.

**Comment by roninsix** [comment]
Ok, will give that a go thanks.

**Comment by roninsix** [comment]
Okay clean install worked, thanks again. I probably should have tried that first ^_^ I'll know next time.
