### ISSUE TITLE
blt 

### ISSUE THREAD

**Issue by walf1992** [JamesWilko/Payday-2-BLT#104]
hi im really angry with this new blt rubbish ive installed no problem now when i start command box pops up whats all that about another issue when i close the game its still running mmm strange as it didnt do this before all the mods dont work wolfhud ngbto custom fov etc etc are all in red boxes no mod options nothing james im not been funny bud and im not knocking you or hating im going to be honest and not lie you have made a right mess of peoples enjoyment not just mine you should of just left it alone now i cant use ngbto so im going to get all the newbies which i dont want and i cant blacklist because theres no mod options theres nothing in there its messed up bud thanks for that

**Comment by BangL** [comment]
how about making your own blt then? good luck.

**Comment by walf1992** [comment]
why even make a new one and anyway fuckoff dude did i ask for your opinion hes pissed alot of people off just because you up his arse div

**Comment by AkiraDaishiyuExe** [comment]
Men, you have to remember that the others mod can't be compatible with the LuaJLT because they didn't have an update for it. For your mods problems, go ask the creators of those mods not BLT. BLT isn't responsible of the LUA change.

**Comment by AkiraDaishiyuExe** [comment]
+ You can't always prevent those errors. The only way to know them is to test the mod.

**Comment by JamesWilko** [comment]
ok

**Comment by walf1992** [comment]
what you talking about james you messed up big time face facts your going to get grieve cant even put wolfhud im not playing it now until you fix this damm issue im done there was no reason for you to update like it just crashed great work not so you have fucked up whats with the boxes i want the old version not boxes and i dont like the slow motion shit james why did you change it and your companions knowing it was going to cause alot of issues i dont enjoy it now red boxes so that means i have to take them all out i dont think so

**Comment by BangL** [comment]
wheb you "can't even put wolfhud" you're probably a retard. its working
fine on my machine :) oh and btw.. I didn't ask for your opinion either.
