### ISSUE TITLE
wolfhud 

### ISSUE THREAD

**Issue by b33croft1992** [JamesWilko/Payday-2-BLT#107]
hi guys due to this new update ive had alot of problems with mods nothing been in mod options i dont know if anybody else is having problems but ive got a crash log for wolfhud 

Application has crashed: C++ exception
mods/WolfHUD/Core.lua:1407: attempt to concatenate a nil value

SCRIPT STACK

_add_version_string() @mods/base/req/core/Hooks.lua:267
original() lib/managers/menu/menunodegui.lua:1771
_setup_item_rows() @mods/base/req/core/Hooks.lua:260
init() core/lib/managers/menu/reference_renderer/coremenunodegui.lua:64
init() lib/managers/menu/menunodegui.lua:68
new() @mods/base/req/utils/UtilsClass.lua:26
show_node() core/lib/managers/menu/reference_renderer/coremenurenderer.lua:81
lib/managers/menu/menurenderer.lua:63
_call_callback() core/lib/managers/menu/coremenulogic.lua:329
core/lib/managers/menu/coremenulogic.lua:96
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:159
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:740
update() lib/setups/menusetup.lua:294
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.323.
	CPU : Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 730 / nvldumd.dll[22.21.13.8541]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8145MB 848KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))

**Comment by PhantomGamers** [comment]
Wolfhud has it's own github page here: https://github.com/Kamikaze94/WolfHUD

**Comment by b33croft1992** [comment]
excellant phantom thankyou still one problem though beardlib failed try again whats the cause of that
