### ISSUE TITLE
Crash upon shooting targets in wicks room with only BLT installed

### ISSUE THREAD

**Issue by enragedpixel** [JamesWilko/Payday-2-BLT#109]
OS: Windows 10 version 1607

How to reproduce: Shoot the targets in John wicks room

Application has crashed: C++ exception
[string "lib/managers/mission/elementunitdamage.lua"]:88: attempt to call method 'override_value_on_element_type' (a nil value)

SCRIPT STACK

clbk() lib/managers/mission/elementunitdamage.lua:72
call() lib/utils/eventlistenerholder.lua:33
damage_damage() lib/units/unitdamage.lua:41
on_collision() lib/units/weapons/raycastweaponbase.lua:2068
_fire_raycast() lib/units/weapons/raycastweaponbase.lua:617
fire() lib/units/weapons/raycastweaponbase.lua:459
trigger_pressed() lib/units/weapons/raycastweaponbase.lua:356
_check_action_primary_attack() lib/units/beings/player/states/playerstandard.lua:4690
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:885
update() lib/units/beings/player/states/playerstandard.lua:413
lib/units/beings/player/playermovement.lua:275

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.323.
	CPU : AMD FX(tm)-6300 Six-Core Processor (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : Radeon (TM) RX 480 Graphics / aticfx32.dll[22.19.662.4]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16382MB 180KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Advanced Micro Devices (1 - E32h-C1 (AMD High Definition Audio Device))

**Comment by fosterbuddy** [comment]
I can confirm - BLT and no mods:

Application has crashed: C++ exception
[string "lib/managers/mission/elementunitdamage.lua"]:88: attempt to call method 'override_value_on_element_type' (a nil value)



SCRIPT STACK

clbk() lib/managers/mission/elementunitdamage.lua:72
call() lib/utils/eventlistenerholder.lua:33
damage_damage() lib/units/unitdamage.lua:41
on_collision() lib/units/weapons/raycastweaponbase.lua:2545
_fire_raycast() lib/units/weapons/raycastweaponbase.lua:617
_fire_raycast() lib/units/weapons/shotgun/shotgunbase.lua:259
fire() lib/units/weapons/raycastweaponbase.lua:459
trigger_held() lib/units/weapons/raycastweaponbase.lua:373
_check_action_primary_attack() lib/units/beings/player/states/playerstandard.lua:4699
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:885
update() lib/units/beings/player/states/playerstandard.lua:413
lib/units/beings/player/playermovement.lua:275


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.323.
	CPU : AMD Ryzen 7 1700X Eight-Core Processor (8 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8541]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     65469MB 332KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (2- Bose USB Audio))

**Comment by JamesWilko** [comment]
Fixed in https://github.com/JamesWilko/Payday-2-BLT-Lua/commit/1c85114868dabef452ee3a709f1d895c141200e8.
