### ISSUE TITLE
Deadlock during initialization of HTTPManager on Windows 7

### ISSUE THREAD

**Issue by joeljuvel** [JamesWilko/Payday-2-BLT#110]
So I did a quick investigation and it seems like it's the static initialization of HTTPManager that's causing a deadlock on Windows 7.

https://github.com/JamesWilko/Payday-2-BLT/blob/d3b6c09598b6d34790de88a4603ea455fa4ecb1a/src/http/http.cpp#L18

**Comment by saladofstones** [comment]
IS there a way to undo this?

**Comment by joeljuvel** [comment]
Yes, just remove or comment out this line, rebuild and it should launch fine on Windows 7.

**Comment by G4RPL3I** [comment]
joeljuvel
So what should I do, to launch Payday 2 with BLT 2.0 mod. Windows 7

**Comment by subzero22** [comment]
For those of us with no coding experience can you give us a step by step guide on how to do this? Or a video on how to rebuild and the programs needed to do it?

**Comment by G4RPL3I** [comment]
subzero22 I will be really greateful, if you make some video or guide :3

**Comment by wilhelmIX** [comment]
G4, im aware that we CAN"T do it by ourselfes, i think that james had do edit IHLPAPI file which is not easy

**Comment by JamesWilko** [comment]
Joel I love you, that seems to work perfectly.

**Comment by G4RPL3I** [comment]
JamesWilko, what does it mean?

**Comment by G4RPL3I** [comment]
JamesWilko I am no good with these things. If you can be honest, tell me what to do exactly.

**Comment by JamesWilko** [comment]
@G4RPL3I The BLT has been updated, you can download the new version here: https://github.com/JamesWilko/Payday-2-BLT/releases/tag/2.1

**Comment by tehsmyers** [comment]
Just tested on Windows 7, the 2.0 tag was failing to start, the 2.1 tag is working. Thanks!

**Comment by victorn1992** [comment]
Thanks James and Joel!!
