### ISSUE TITLE
Payday 2 will not launch when having BLT 2 installed

### ISSUE THREAD

**Issue by PimpWhiskers** [JamesWilko/Payday-2-BLT#111]
Title says it all

**Comment by SilentAvenger12** [comment]
pimp read other issues instead of spamming about the same thing again its  Win 7 issue which im sure you probly have james knows this and is working on a fix so just wait

**Comment by saladofstones** [comment]
Is there a fix for it?

**Comment by AkiraDaishiyuExe** [comment]
No fix for now but be patient

**Comment by RichtofensCat** [comment]
How would i find out when there is an update? I don't use this website much.

**Comment by akirathegunkuma** [comment]
https://github.com/JamesWilko/Payday-2-BLT/releases
