### ISSUE TITLE
Game starts fine with BLT 2.0 installed but BLT fails to start

### ISSUE THREAD

**Issue by ZombieZMB** [JamesWilko/Payday-2-BLT#113]
After replacing the older version of BLT when I would start the game it would launch fine but it would act as if I am playing a unmodded version of Payday 2. When I check the console that pops up in the background [this](http://i.imgur.com/ybTjsV3.png) would be spammed in the console 3 times. 

Edit: this seems to be fixed with BLT 2.1 :D

**Comment by virusapex** [comment]
Same is happening to me. Win 10, VC 2013 x86 is installed, previous version of BLT worked fine. Even cleaned up the "base" folder, still no luck.
