### ISSUE TITLE
Crash when joining game

### ISSUE THREAD

**Issue by MinetaS** [JamesWilko/Payday-2-BLT#115]
I tested without any mod. Only with BLT is the game crashed.
Below is the log;

Sat Sep 02 23:48:40 2017

Application has crashed: C++ exception
[string "lib/managers/missionmanager.lua"]:288: attempt to call method 'client_on_executed' (a nil value)

SCRIPT STACK

lib/network/handlers/unitnetworkhandler.lua:558

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.326.
	CPU : Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 11.0 
	GPU : Intel(R) HD Graphics 4000 / nvumdshim.dll[10.18.13.6191]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8079MB 404KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers(Realtek High Definition Audio))

Appreciate your efforts.

**Comment by JamesWilko** [comment]
Fixed in https://github.com/JamesWilko/Payday-2-BLT-Lua/commit/1c85114868dabef452ee3a709f1d895c141200e8.
