### ISSUE TITLE
CHOOSE LANGUAGE - NOT WORK

### ISSUE THREAD

**Issue by chromKa** [JamesWilko/Payday-2-BLT#117]
+ if we go to BLT MODS and go back heister dissapeared (bug)

**Comment by namcancode** [comment]
mod keybind dont work

**Comment by lixal** [comment]
Same to me

**Comment by dive-bomber** [comment]
You can add mod_options back if you follow [this](http://steamcommunity.com/app/218620/discussions/15/1474221865195473650/) thread.

**Comment by chromKa** [comment]
Whats about choose language?

**Comment by JamesWilko** [comment]
BLT Lua issue, was fixed. https://github.com/JamesWilko/Payday-2-BLT-Lua/issues/17
