### ISSUE TITLE
Mod options missing on game...

### ISSUE THREAD

**Issue by akirathegunkuma** [JamesWilko/Payday-2-BLT#118]
Here is an exemple, i need to get on a game to modified MUI and i can't, i didn't find Mod options in the options :/

**Comment by TakRiuto** [comment]
You should expect the developer to update the mod, it's not BLT's fault

**Comment by akirathegunkuma** [comment]
I don't think so, because the other i have like Bag Contour and others have the same feature as MUI.

**Comment by RcrossF** [comment]
Same problem here, doesn't seem like blt is being loaded

EDIT: Fixed by manually updating to the newest release

**Comment by BangL** [comment]
bag contour got updated for blt2, mui didn't yet

**Comment by akirathegunkuma** [comment]
From MUI Steam Discussion : 

> EDIT: Pushed new revision(s), some behoodyhoo goin' on with just about everything.
> Waiting for BLT to stabilize until I commit any larger changes.
> 
> In-game downloader borks sideways and deletes the mod on my attempts, download manually if it fails.
> Download.[download.paydaymods.com]

It's update but bag contour have normally an in-game option and i didn't have this option.

**Comment by ghost** [comment]
It's because the mods aren't updated. The new BLT changed the "parent_menu_id" from "lua_mod_options_menu" to "blt_options". Any mod with the old value won't have the menu appear. Until the mods get updated you can fix it manually for now by changing the value yourself and they should appear in mod options.

**Comment by gregor-dietrich** [comment]
You guys don't understand what his problem is. He means that mod options are no longer accessible from within a heist (pressing escape), only from the main menu or pre-lobby.
This is **not** related to mods not being updated, this is a change introduced in BLT 2 and I don't understand it either.
Basically the same as this issue: https://github.com/JamesWilko/Payday-2-BLT/issues/120

**Comment by akirathegunkuma** [comment]
Thanks xtakku, i wanted to comment about that but you're fast enough ^^ Yes, i was talking about mod options in a heist. Sorry for the confusion

**Comment by JamesWilko** [comment]
Added in https://github.com/JamesWilko/Payday-2-BLT-Lua/commit/89240f957c22303141a50efc91d8b4b8fbc9a96c, will be live in next update.
