### ISSUE TITLE
No mod options in game

### ISSUE THREAD

**Issue by OSkomodo** [JamesWilko/Payday-2-BLT#120]
When you playing heist you can't open mod options menu and change mod options. Like if you want change something in wolfhud you need to quit heist, go to menu, change it and then reconnect, it's not that easy. I want to configurate my wolfhud but i need restart heist every time i want to see how new size, colour or w/e looks like in game. 
Add mod options in game pls

**Comment by dive-bomber** [comment]
http://steamcommunity.com/app/218620/discussions/15/1474221865195473650/

**Comment by JamesWilko** [comment]
Fixed in https://github.com/JamesWilko/Payday-2-BLT-Lua/commit/89240f957c22303141a50efc91d8b4b8fbc9a96c, will be in in the next update.
