### ISSUE TITLE
BLT Config Compatibility Broken After RAID: WW2 related update

### ISSUE THREAD

**Issue by justalemon** [JamesWilko/Payday-2-BLT#121]
I updated the game yesterday and magically the "BLT window" on the main menu did not show up and i didn't found the mod options into the config.

When i played a heist the game did not load any of the mods, i double checked that the game directory has the "IPHLPAPI.dll" file.

The DLL was there, so to avoid issues i moved the mods folder to the desktop and copied a fresh "mods" folder. After that the game showed up the BLT options and pop ups, so i tried to move back mod by mod to see what is crashing.

The problem was the old configs of ALL mods, so i have to reconfigure everything.

What was that?

Edit: Yesterday was 1.08, today is 2.1

Note: The MD5 of my "IPHLPAPI.dll/2.1" is:
3799ED2CEDACC4B3611DFC97C547C634

**Comment by PhantomGamers** [comment]
Mod configuration options are saved in the mods/saves directory

**Comment by JamesWilko** [comment]
Your mods save files were not transferred across form the saves directory in mods.
