### ISSUE TITLE
BLT 2.1  win7 the game is opening but closing on the installation screen

### ISSUE THREAD

**Issue by Pinti-pnda** [JamesWilko/Payday-2-BLT#124]
the payday 2 is opening but closing on the installation screen JAMES WİLKO help me pls

**Comment by JamesWilko** [comment]
What is the installation screen? Can you run the game in general without the BLT?

**Comment by Death14353** [comment]
My game with this BLT runs normally to the point where on the screen is written "press anything to continue" then it closes. What could cause this issue?

**Comment by BangL** [comment]
broken mods..clean up. and provide crashlogs if you want more help

**Comment by Death14353** [comment]
I erased the post cause i repaired it but thx for answear.
