### ISSUE TITLE
PD2 PPR

### ISSUE THREAD

**Issue by Expelll** [JamesWilko/Payday-2-BLT#126]
I cant seem to access the menu even from the lobby screen, pressing numpad 1 does nothing for me

**Comment by offyerrocker** [comment]
What was Numpad 1 bound to? I thought the menu was hard-coded bound to ESC. I'm not sure I understand the issue.
[JSON keybinds don't currently save, however. Maybe that's the issue?](https://github.com/JamesWilko/Payday-2-BLT/issues/102)

**Comment by Expelll** [comment]
I did a reinstall and it suddenly started working so I dont know what the issue was
