### ISSUE TITLE
got a massive crash log 

### ISSUE THREAD

**Issue by b33croft1992** [JamesWilko/Payday-2-BLT#128]
what does this mean 

deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
deep_clone() core/lib/utils/coretable.lua:34
_notify() lib/utils/messagesystem.lua:45
update() lib/utils/messagesystem.lua:74
update() lib/managers/mutatorsmanager.lua:108
update() lib/setups/setup.lua:749
update() lib/setups/gamesetup.lua:650
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.326.
	CPU : Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 730 / nvldumd.dll[22.21.13.8541]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8145MB 848KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))

**Comment by BangL** [comment]
looks like an infinite loop to me

**Comment by JamesWilko** [comment]
Reopen the issue if this can be confirmed to be a BLT issue.
