### ISSUE TITLE
[REQUEST] Add the ability to edit mods in game again

### ISSUE THREAD

**Issue by Canpake59** [JamesWilko/Payday-2-BLT#129]
I'm pretty sure that you were able to edit mods when you were in game, but with the new BLT update you can't do that anymore. Is this permanent or will we get the option to do that again

**Comment by offyerrocker** [comment]
[This will be fixed in the coming update. ](https://github.com/JamesWilko/Payday-2-BLT-Lua/commit/89240f957c22303141a50efc91d8b4b8fbc9a96c)

**Comment by Canpake59** [comment]
Awesome! Thanks for the response!
