### ISSUE TITLE
Allow setting Priority for JSON menu's

### ISSUE THREAD

**Issue by Kilandor** [JamesWilko/Payday-2-BLT#13]
Currently you can not set a priority in any way for JSON menu's

It would be nice to set Priority not only for the items in a menu so that you can organize them with coded and other json menu's. It would be nice to set the priority for the menu itself in its parent

```json
{
	"menu_id" : "json_example_menu",
	"parent_menu_id" : "lua_mod_options_menu",
	"title" : "my_custom_menu",
	"description" : "my_custom_menu_desc",
	"priority" : 4,
	"items" : [
	{
		"type" : "toggle",
		"id" : "json_menu_toggle",
		"title" : "json_item_toggle",
		"description" : "json_item_toggle_desc",
		"callback" : "callback_test_toggle",
		"value" : "toggle_value",
		"default_value" : false,
		"priority" : 10
	}
	]
}
```

In this example the first priority would be set for the AddMenuItem for adding this new menu to its parent

Then the ones for the items would be set well for them in their menu

**Comment by JamesWilko** [comment]
Added in yesterdays updates.
