### ISSUE TITLE
BLT don't working(again)

### ISSUE THREAD

**Issue by TangoWhiskyFoxtrot** [JamesWilko/Payday-2-BLT#131]
I'm Install new version of BLT(2.1), but mods dont working. Somebody say, what im doing wrong

**Comment by offyerrocker** [comment]
Be specific with your problem, beyond simply saying "mods aren't working." Is it that BLT mods don't appear?

**Comment by Chaos614** [comment]
I think what they're trying to say is that their BLT mods aren't showing up in Payday 2
But I think that it could be the Aldstone's Heritage update breaking BLT, which I heard of it doing (Unless that got fixed in 2.1).
