### ISSUE TITLE
2.1 Still CTDs

### ISSUE THREAD

**Issue by mukyuuhikuu** [JamesWilko/Payday-2-BLT#132]
Despite the update i still get the CTD with this update,

[Here is my Computer specs if needed to pinpoint the crash](https://github.com/JamesWilko/Payday-2-BLT/files/1278614/MUKYUUHIKUU-PC.txt)

[And this is the .mdmp dump](https://github.com/JamesWilko/Payday-2-BLT/files/1278613/CTD.zip)

**Comment by JamesWilko** [comment]
Please try BLT 2.2 and reopen the issue if this still persists.
