### ISSUE TITLE
BLT 2.2 dosen't work again for windows 7

### ISSUE THREAD

**Issue by ArthurBeNz** [JamesWilko/Payday-2-BLT#134]
Ok,i have windows 7 and blt 2.2 dosen't work again like BLT 2,payday 2 open in processes and on steam appear i play payday 2,but on monitor dosen't show anything,please help !

**Comment by AmperAndSand** [comment]
I can confirm that this also happens to me on Windows 7. Reverting back to 2.1's IPHLPAPI.dll will fix the issue.

**Comment by ArthurBeNz** [comment]
Ok,thanks,but i will wait for creator i think to fix it again

**Comment by MrSkittlesROTR** [comment]
Works fine for me on win7 home premium.

**Comment by ArthurBeNz** [comment]
Guys i fixed it, u need to reinstall the game and then u need to download BLT 2.1 and need to update from update manager and will work,i hope i help u guys

**Comment by JamesWilko** [comment]
Can you try redownload the latest release and seeing if the issue still persists? https://github.com/JamesWilko/Payday-2-BLT/releases

**Comment by AmperAndSand** [comment]
It now works on Windows 7 in my case. I've just redownloaded 2.2. It seems that there is a difference between IPHLPAPI.dll in the 2.2 initial release and the current one.

**Comment by BeepIsla** [comment]
Downloaded it around 30 minutes after release and it didn't work. Redownloaded it and now it works.

**Comment by AmperAndSand** [comment]
The hash of the 2.2 initial release's IPHLPAPI.dll and the current one is different. The current IPHLPAPI.dll is the same as 2.1's.

**Comment by ArthurBeNz** [comment]
Now works guy,u can close this.
