### ISSUE TITLE
"ModPath" always returning "mods/base/"

### ISSUE THREAD

**Issue by cineafx** [JamesWilko/Payday-2-BLT#137]
A way to check it is: `log(ModPath)`
This outputs into the console `PM Lua: mods/base/` no matter whether run via hook, persist_script or keybind.

Tested on: BLT_release_r7_r18 (2.2)

**Comment by JamesWilko** [comment]
ModPath is only updated for hook files, not for persist scripts or keybinds. But I can't reproduce this issue anyway, ModPath is always returning the intended value.

**Comment by cineafx** [comment]
Okay I wasn't aware that ModPath only works for hook files. It had been working fine for me in persist scripts and keybinds some time ago.
