### ISSUE TITLE
crash on clicking on update tab in mods viewer

### ISSUE THREAD

**Issue by Scorpion2606** [JamesWilko/Payday-2-BLT#139]
BLT shows mods updates are available and when i click on update tab in mods viewer the game crashes..
here's the crashlog
Application has crashed: C++ exception
mods/base/req/ui/BLTUIControls.lua:313: attempt to call method 'IsCritical' (a nil value)

SCRIPT STACK

new() /req/utils/UtilsClass.lua:26
_setup() /req/ui/BLTDownloadManagerGui.lua:125
init() /req/ui/BLTDownloadManagerGui.lua:34
new() /req/utils/UtilsClass.lua:26
create() /req/ui/BLTDownloadManagerGui.lua:257
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() /lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:159
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:740
update() lib/setups/menusetup.lua:294
update() /lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537

Callstack:

     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
Current thread: Main

System information:
Application version : 1.76.327.
CPU : Intel(R) Pentium(R) Dual CPU E2200 @ 2.20GHz (1 core); SSE; SSE2; SSE3; SSSE3
DirectX : 10.0
GPU : AMD Radeon HD 5700 Series / aticfx32.dll[8.17.10.1404]
Language : @id94cca2fdaccfc2cd@
Memory : 3069MB 260KB
OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
Physics : threaded
Renderer : DX9 threaded
Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by BangL** [comment]
wasn't one invalid bug report enough? ok
it is fixed already. just do the update.

**Comment by Scorpion2606** [comment]
Working after the update.. Thanks for your work
