### ISSUE TITLE
Mod-made global tables are not kept throughout the game

### ISSUE THREAD

**Issue by thatguyfrombb** [JamesWilko/Payday-2-BLT#14]
Hi! First of all, thanks for this hook :)
I'm trying to make a mod which requires a table to be initialized when the game is run, and the table to be kept for as long as the game is running. I've got an example here: https://github.com/thatguyfrombb/BLT-KeepTable-Test

In the log I can see that my table (bltKeepTable_data, a global) disappears when I exit a contract, either by quitting to menu or completing it succesfully. In the example I've used some simple static data (a string, "Hey, here's your data!") and is never modified by anything. Sadly, my mod (whenever it's done), will require the addition of dynamic data, so keeping it in a static file and loading it each time is not an option. I've also tried both keeping the table in LocalizationManager and creating the global table from LocalizationManager:init(), checking first if it did exist so I didn't overwrite it. In those two cases, I got rid of the persist script, but the result is exactly the same.

I'm not sure if it's me doing anything wrong or if there's any other way to do this, but I've tried everything I could think of, so I'm coming straight to you guys :)

**Comment by thatguyfrombb** [comment]
After checking the code for BLT, seems like a case of "NOTABUG - WONTFIX" as the game just reset/recreates the lua state when you get to the main menu. That sucks :(

**Comment by JamesWilko** [comment]
Yep, the state from menu to game and back again isn't the same, so the only way to keep data between them is to save it and load it again afterwards.
You could look for something that doesn't get reloaded and try piggybacking off of it, but that's going to be hacky at best.

**Comment by thatguyfrombb** [comment]
Thank you! I'll post here if I find something to notify me for saving or something to piggyback.

**Comment by SirWaddles** [comment]
We could potentially add a global data-store to BLT itself, it wouldn't be able to store lua references and objects etc, but strings, integers and data I could manage.

[There's a whitepaper on this as well](http://www.inf.puc-rio.br/~roberto/docs/ry08-05.pdf)

**Comment by SirWaddles** [comment]
Payday is weird. Probably not going to solve. It looked into this briefly and it seems intrinsically complicated for both the hook developer (this old sod) and any potential mod developer. Anything with an object reference would have to be seralized.

Might look into it later, but I'm gonna close for now.
