### ISSUE TITLE
Mod Options Problem

### ISSUE THREAD

**Issue by Vengeance2** [JamesWilko/Payday-2-BLT#140]
i have CompactHUD, Custom Hitmarkers installed and no mod options appear for this two mods

**Comment by BangL** [comment]
that means these mods are most likely not updated for blt2, could that be ?

with the blt2 update the menu id of the blt options menu changed, (along with several other breaking changes of course) thats why.
you can try changing the old id to the new one, that would bring the menu back.
other problems might follow though.

the old menu id was "lua_mod_options_menu" and needs to be replaced with "blt_options".

**Comment by JamesWilko** [comment]
Not a BLT issue.
