### ISSUE TITLE
Changing Icon of Auto-Updatable Mods Will Make Them Delete When It Updates

### ISSUE THREAD

**Issue by Sydch** [JamesWilko/Payday-2-BLT#141]

**Comment by JamesWilko** [comment]
Not an issue. You are modifying the mod, which removes your changes when it updates.

**Comment by Sydch** [comment]
It's an issue, because it never happened to me back in the day with the original BLT. It completely wipes the mod, not just the icon.

**Comment by BangL** [comment]
old blt was different. what a surprise.
new blt does not allow any changes at all. we have to accept that.
in fact just changing a single character in any file already triggers an update.

**Comment by Sydch** [comment]
I know it was different and was a nuke to all mods out there, thanks for your support. The point that I've saying it completely wipes mod, not just updates them.
