### ISSUE TITLE
BLT 2.2 does not work for me on Windows 7

### ISSUE THREAD

**Issue by mclarenf1lm15** [JamesWilko/Payday-2-BLT#142]
The game will start up and I can get to the main menu, but it acts like BLT isn't even installed. Reverting back to BLT 2.1 fixes it, however with BLT 2.1, clicking the red update button will crash the game.

**Comment by BangL** [comment]
logs?

**Comment by mclarenf1lm15** [comment]
Sat Sep 09 14:01:46 2017


Application has crashed: C++ exception
mods/base/req/ui/BLTUIControls.lua:313: attempt to call method 'IsCritical' (a nil value)



SCRIPT STACK

new() @mods/base/req/utils/UtilsClass.lua:26
_setup() @mods/base/req/ui/BLTDownloadManagerGui.lua:125
init() @mods/base/req/ui/BLTDownloadManagerGui.lua:34
new() @mods/base/req/utils/UtilsClass.lua:26
create() @mods/base/req/ui/BLTDownloadManagerGui.lua:257
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:159
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:740
update() lib/setups/menusetup.lua:294
_update() @mods/base/lua/MenuSetup.lua:6
update() @mods\PocoHud3\poco\common.lua:310
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.327.
	CPU : Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 1080 / nvd3dum.dll[22.21.13.8541]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16342MB 468KB
	OS : 6.1.7600 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : C-MEDIA Inc. (Speakers (USB Audio Device))

**Comment by mclarenf1lm15** [comment]
Never mind. I figured it out. It was the mod "Better Bots" with it's newest update that some how broke BLT. 
This can be closed now.

**Comment by BangL** [comment]
you're not having the latest base folder, which fixes it.
