### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Punky69** [JamesWilko/Payday-2-BLT#144]
mod is installed but does not work here is log

> `12:49:02

 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:49:04 AM Log:  (..\src\http\http.cpp:44) CURL_INITD
12:49:04 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:49:05 AM Lua: [BLT] Setup...
12:49:05 AM Lua: [BLT] Loading module: 	BLTLogs
12:49:05 AM Lua: [BLT] Loading module: 	BLTModManager
12:49:05 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:49:05 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:49:05 AM Lua: [BLT] Loading module: 	BLTLocalization
12:49:05 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:49:05 AM Lua: [BLT] Loading mods for state: table: 0x001d0440
12:49:05 AM Lua: [BLT] Loading mod: base
12:49:05 AM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
12:49:05 AM Lua: [BLT] Setting up mod: 	base
12:49:05 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:49:05 AM Lua: [BLT] Setup...
12:49:05 AM Lua: [BLT] Loading module: 	BLTLogs
12:49:05 AM Lua: [BLT] Loading module: 	BLTModManager
12:49:05 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:49:05 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:49:05 AM Lua: [BLT] Loading module: 	BLTLocalization
12:49:05 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:49:05 AM Lua: [BLT] Loading mods for state: table: 0x001d0460
12:49:05 AM Lua: [BLT] Loading mod: base
12:49:05 AM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
12:49:05 AM Lua: [BLT] Setting up mod: 	base
12:49:05 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:49:05 AM Lua: [BLT] Setup...
12:49:05 AM Lua: [BLT] Loading module: 	BLTLogs
12:49:05 AM Lua: [BLT] Loading module: 	BLTModManager
12:49:05 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:49:05 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:49:05 AM Lua: [BLT] Loading module: 	BLTLocalization
12:49:05 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:49:05 AM Lua: [BLT] Loading mods for state: table: 0x20f12c60
12:49:05 AM Lua: [BLT] Loading mod: base
12:49:05 AM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
12:49:05 AM Lua: [BLT] Setting up mod: 	base
12:49:14 AM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
12:49:14 AM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt - 1181
12:49:14 AM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
12:49:14 AM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
12:49:14 AM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2bltdll - 1182
12:49:14 AM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
12:49:18 AM Lua: [Updates] Received update data for 'payday2blt'
12:49:19 AM Lua: [Updates] Comparing hash data:
Server: d3b664861b3d66a940f9c59f8329128a82dd028f09d6749849beefb0b9cb490b
 Local: d3b664861b3d66a940f9c59f8329128a82dd028f09d6749849beefb0b9cb490b
12:49:19 AM Lua: [Updates] Received update data for 'payday2bltdll'
12:49:19 AM Lua: [Updates] Comparing hash data:
Server: 4f7bd43c1dd3d7ce856d3182e6f971980d0c59aeb3b17231eb9c2f3b5cf3a545
 Local: 4f7bd43c1dd3d7ce856d3182e6f971980d0c59aeb3b17231eb9c2f3b5cf3a545
12:49:23 AM Log:  (..\src\http\http.cpp:49) CURL CLOSED
12:49:30 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:49:32 AM Log:  (..\src\http\http.cpp:44) CURL_INITD
12:49:32 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:49:32 AM Lua: [BLT] Setup...
12:49:32 AM Lua: [BLT] Loading module: 	BLTLogs
12:49:32 AM Lua: [BLT] Loading module: 	BLTModManager
12:49:32 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:49:32 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:49:32 AM Lua: [BLT] Loading module: 	BLTLocalization
12:49:32 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:49:32 AM Lua: [BLT] Loading mods for state: table: 0x001d0440
12:49:32 AM Lua: [BLT] Loading mod: base
12:49:32 AM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
12:49:32 AM Lua: [BLT] Setting up mod: 	base
12:49:32 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:49:32 AM Lua: [BLT] Setup...
12:49:32 AM Lua: [BLT] Loading module: 	BLTLogs
12:49:32 AM Lua: [BLT] Loading module: 	BLTModManager
12:49:32 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:49:32 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:49:32 AM Lua: [BLT] Loading module: 	BLTLocalization
12:49:32 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:49:32 AM Lua: [BLT] Loading mods for state: table: 0x001d0460
12:49:32 AM Lua: [BLT] Loading mod: base
12:49:32 AM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
12:49:32 AM Lua: [BLT] Setting up mod: 	base
12:49:32 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:49:32 AM Lua: [BLT] Setup...
12:49:32 AM Lua: [BLT] Loading module: 	BLTLogs
12:49:32 AM Lua: [BLT] Loading module: 	BLTModManager
12:49:32 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:49:32 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:49:32 AM Lua: [BLT] Loading module: 	BLTLocalization
12:49:32 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:49:32 AM Lua: [BLT] Loading mods for state: table: 0x20710460
12:49:32 AM Lua: [BLT] Loading mod: base
12:49:32 AM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
12:49:32 AM Lua: [BLT] Setting up mod: 	base
12:49:51 AM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
12:49:51 AM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt - 1329
12:49:51 AM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
12:49:51 AM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
12:49:51 AM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2bltdll - 1330
12:49:51 AM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
12:49:55 AM Lua: [Updates] Received update data for 'payday2blt'
12:49:55 AM Lua: [Updates] Comparing hash data:
Server: d3b664861b3d66a940f9c59f8329128a82dd028f09d6749849beefb0b9cb490b
 Local: d3b664861b3d66a940f9c59f8329128a82dd028f09d6749849beefb0b9cb490b
12:49:55 AM Lua: [Updates] Received update data for 'payday2bltdll'
12:49:55 AM Lua: [Updates] Comparing hash data:
Server: 4f7bd43c1dd3d7ce856d3182e6f971980d0c59aeb3b17231eb9c2f3b5cf3a545
 Local: 4f7bd43c1dd3d7ce856d3182e6f971980d0c59aeb3b17231eb9c2f3b5cf3a545
12:50:08 AM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
12:50:08 AM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt - 1604
12:50:08 AM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
12:50:08 AM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
12:50:08 AM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2bltdll - 1602
12:50:08 AM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
12:50:12 AM Lua: [Updates] Received update data for 'payday2bltdll'
12:50:12 AM Lua: [Updates] Comparing hash data:
Server: 4f7bd43c1dd3d7ce856d3182e6f971980d0c59aeb3b17231eb9c2f3b5cf3a545
 Local: 4f7bd43c1dd3d7ce856d3182e6f971980d0c59aeb3b17231eb9c2f3b5cf3a545
12:50:12 AM Lua: [Updates] Received update data for 'payday2blt'
12:50:12 AM Lua: [Updates] Comparing hash data:
Server: d3b664861b3d66a940f9c59f8329128a82dd028f09d6749849beefb0b9cb490b
 Local: d3b664861b3d66a940f9c59f8329128a82dd028f09d6749849beefb0b9cb490b
12:50:15 AM Lua: [BLT] Performing save...
12:50:15 AM Lua: [BLT] Save complete? true
12:50:16 AM Lua: [BLT] Performing save...
12:50:16 AM Lua: [BLT] Save complete? true
12:50:29 AM Lua: [Downloads] Flushing complete downloads...
12:51:25 AM Lua: [BLT] Performing save...
12:51:25 AM Lua: [BLT] Save complete? true
12:51:26 AM Lua: [BLT] Performing save...
12:51:26 AM Lua: [BLT] Save complete? true
12:51:33 AM Log:  (..\src\http\http.cpp:49) CURL CLOSED
12:51:40 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:51:42 AM Log:  (..\src\http\http.cpp:44) CURL_INITD
12:51:42 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:51:42 AM Lua: [BLT] Setup...
12:51:42 AM Lua: [BLT] Loading module: 	BLTLogs
12:51:42 AM Lua: [BLT] Loading module: 	BLTModManager
12:51:42 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:51:42 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:51:42 AM Lua: [BLT] Loading module: 	BLTLocalization
12:51:42 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:51:42 AM Lua: [BLT] Loading mods for state: table: 0x001d0440
12:51:42 AM Lua: [BLT] Loading mod: base
12:51:42 AM Lua: [BLT] Setting up mod: 	base
12:51:42 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:51:42 AM Lua: [BLT] Setup...
12:51:42 AM Lua: [BLT] Loading module: 	BLTLogs
12:51:42 AM Lua: [BLT] Loading module: 	BLTModManager
12:51:42 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:51:42 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:51:42 AM Lua: [BLT] Loading module: 	BLTLocalization
12:51:42 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:51:42 AM Lua: [BLT] Loading mods for state: table: 0x001d0460
12:51:42 AM Lua: [BLT] Loading mod: base
12:51:42 AM Lua: [BLT] Setting up mod: 	base
12:51:42 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:51:42 AM Lua: [BLT] Setup...
12:51:42 AM Lua: [BLT] Loading module: 	BLTLogs
12:51:42 AM Lua: [BLT] Loading module: 	BLTModManager
12:51:42 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:51:42 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:51:42 AM Lua: [BLT] Loading module: 	BLTLocalization
12:51:42 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:51:42 AM Lua: [BLT] Loading mods for state: table: 0x20f31fa0
12:51:42 AM Lua: [BLT] Loading mod: base
12:51:42 AM Lua: [BLT] Setting up mod: 	base
12:51:52 AM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
12:51:52 AM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt - 1034
12:51:52 AM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
12:51:52 AM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
12:51:52 AM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2bltdll - 1033
12:51:52 AM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
12:51:52 AM Lua: [Updates] Received update data for 'payday2bltdll'
12:51:52 AM Lua: [Updates] Comparing hash data:
Server: 4f7bd43c1dd3d7ce856d3182e6f971980d0c59aeb3b17231eb9c2f3b5cf3a545
 Local: 4f7bd43c1dd3d7ce856d3182e6f971980d0c59aeb3b17231eb9c2f3b5cf3a545
12:51:52 AM Lua: [Updates] Received update data for 'payday2blt'
12:51:52 AM Lua: [Updates] Comparing hash data:
Server: d3b664861b3d66a940f9c59f8329128a82dd028f09d6749849beefb0b9cb490b
 Local: d3b664861b3d66a940f9c59f8329128a82dd028f09d6749849beefb0b9cb490b
12:52:00 AM Lua: [BLT] Performing save...
12:52:00 AM Lua: [BLT] Save complete? true
12:52:06 AM Lua: [BLT] Performing save...
12:52:06 AM Lua: [BLT] Save complete? true
12:52:43 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:52:43 AM Lua: [BLT] Setup...
12:52:43 AM Lua: [BLT] Loading module: 	BLTLogs
12:52:43 AM Lua: [BLT] Loading module: 	BLTModManager
12:52:43 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:52:43 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:52:43 AM Lua: [BLT] Loading module: 	BLTLocalization
12:52:43 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:52:43 AM Lua: [BLT] Loading mods for state: table: 0x3bca2c60
12:52:43 AM Lua: [BLT] Loading mod: base
12:52:43 AM Lua: [BLT] Setting up mod: 	base
12:52:43 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:52:43 AM Lua: [BLT] Setup...
12:52:43 AM Lua: [BLT] Loading module: 	BLTLogs
12:52:43 AM Lua: [BLT] Loading module: 	BLTModManager
12:52:43 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:52:43 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:52:43 AM Lua: [BLT] Loading module: 	BLTLocalization
12:52:43 AM Lua: [BLT] Cle`

**Comment by JamesWilko** [comment]
Please make sure you are running the latest BLT, and check if there are any crash logs generated in `%localappdata%/PAYDAY 2/crash.txt`. Reopen the issue if there are.
