### ISSUE TITLE
BLT UI Controls Crash

### ISSUE THREAD

**Issue by xavieerx** [JamesWilko/Payday-2-BLT#147]
Sat Sep 09 19:58:58 2017

Application has crashed: C++ exception
mods/base/req/ui/BLTUIControls.lua:313: attempt to call method 'IsCritical' (a nil value)

SCRIPT STACK

new() @mods/base/req/utils/UtilsClass.lua:26
_setup() @mods/base/req/ui/BLTDownloadManagerGui.lua:125
init() @mods/base/req/ui/BLTDownloadManagerGui.lua:34
new() @mods/base/req/utils/UtilsClass.lua:26
create() @mods/base/req/ui/BLTDownloadManagerGui.lua:257
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:159
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:740
update() lib/setups/menusetup.lua:294
_update() @mods/base/lua/MenuSetup.lua:6
update() @mods\PocoHud3\poco\common.lua:309
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

**Comment by xavieerx** [comment]
also i deleted pocohud and same crash ;u

**Comment by BangL** [comment]
clearly not using the latest "base" lua files. this was fixed long ago

**Comment by xavieerx** [comment]
oh thanks im stupid :)
