### ISSUE TITLE
Adding integrity checking to downloaded contents

### ISSUE THREAD

**Issue by kkspeed** [JamesWilko/Payday-2-BLT#15]
I'm experiencing an issue where the mod's update pack is not complete. Probably it's better to verify mod updates / downloaded zip file with MD5 or SHA1. Also, as far as I see in the HTTP code, it does not check HTTP response code. If the connection is aborted mid way, it could result in a broken zip file - extracting which to mods dir will lead to a black screen the next time game starts.

**Comment by SirWaddles** [comment]
I was gonna do this.

I forgot. Sorry.
Will get back to you.

**Comment by SirWaddles** [comment]
Actually, would it be better if I just added a sha1/md5 function that lua can use, and echoed out the HTTP request details in the dohttpreq callback?
