### ISSUE TITLE
Publicly ask "don't complain about in-game BLT issues here"

### ISSUE THREAD

**Issue by ghost** [JamesWilko/Payday-2-BLT#151]
It seems a lot of the issues in this repository are just people complaining that their PAYDAY 2 won't start or that BLT is broken. A public service announcement could be made asking for people not to do that here and instead focus on the actual contents of the repository. I understand I sound really hypocritical right now, I just feel bad that the contributors to BLT have to deal with complaints in the wrong place.

**Comment by JamesWilko** [comment]
Not an issue.
