### ISSUE TITLE
[string "lib/managers/syncmanager.lua"]:22: attempt to index a nil value

### ISSUE THREAD

**Issue by TheBoneJuiceMan** [JamesWilko/Payday-2-BLT#159]
Sun Oct 22 15:17:57 2017

Application has crashed: C++ exception
[string "lib/managers/syncmanager.lua"]:22: attempt to index a nil value

SCRIPT STACK

add_synced_vault_cash() lib/managers/syncmanager.lua:150
perform_sync() lib/units/props/safehousevaultmoneystacks.lua:101
set_active_tier() lib/units/props/safehousevaultmoneystacks.lua:87
_setup() lib/units/props/safehousevaultmoneystacks.lua:78
lib/units/props/safehousevaultmoneystacks.lua:34
safe_spawn_unit() =[C]
_create_statics_unit() core/lib/utils/dev/editor/coreworlddefinition.lua:921
create() core/lib/utils/dev/editor/coreworlddefinition.lua:522
create_world() core/lib/utils/dev/editor/worldholder.lua:110
init_game() lib/setups/gamesetup.lua:592
core/lib/setups/coresetup.lua:402

I can't figure out what in particular is causing payday 2 to crash, and I can't find syncmanager.lua, is there something wrong??? I figure this would be a similar problem to the whole networking issue. But when I try to play on singleplayer and go to my safehouse, I keep on crashing at the loading screen. I need someone to at least respond/help me with this.

**Comment by JamesWilko** [comment]
Can not reproduce, not a BLT issue.
