### ISSUE TITLE
Getting a crash with the new update.

### ISSUE THREAD

**Issue by hugojmaia** [JamesWilko/Payday-2-BLT#163]
Game crashes when I press F to mark something and nothing's in range.

`Application has crashed: C++ exception
mods/Keepers/lua/playerstandard.lua:36: attempt to index a nil value

SCRIPT STACK

_start_action_intimidate() lib/units/beings/player/states/playerstandard.lua:3618
_check_action_interact() lib/units/beings/player/states/playerstandard.lua:2242
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:910
update_original() lib/units/beings/player/states/playerstandard.lua:414
update() @mods/Burstfire/burstfire.lua:135
lib/units/beings/player/playermovement.lua:275

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.80.413.
	CPU : AMD Athlon(tm) X4 750 Quad Core Processor (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 10.0 
	GPU : Radeon(TM) RX 460 Graphics / aticfx32.dll[22.19.162.4]
	Language : english
	Memory :     8147MB 408KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

`

**Comment by asdf1324** [comment]
It's something with the mod 'Keepers', not the BLT itself

**Comment by JamesWilko** [comment]
Not a BLT issue.
