### ISSUE TITLE
New Payday Update

### ISSUE THREAD

**Issue by zackman0010** [JamesWilko/Payday-2-BLT#17]
In the news about the new Payday update, they specifically mentioned that any modded game WILL crash.
The direct quote: http://steamcommunity.com/games/218620/announcements/detail/101677733981368160
"PLEASE NOTE: IF YOU HAVE MODS, YOU WILL CRASH!"
I was warned beforehand about this problem and uninstalled the hook before downloading the update, so I unfortunately do not have any log files available for you. I can reinstall it and purposely make my game crash if you would like the files to examine and to see if the hook is where the crash occurs or if it's only the mods.

**Comment by thatguyfrombb** [comment]
In my experience, BLT is not crashing or having any problems *at all*. Goonhud and PocoHUD maybe, but BLT is fine. In fact, I'm pretty sure I saw CommanderCH's game crash on twitch on the day of release due to PocoHUD.

**Comment by zackman0010** [comment]
Perhaps it is the mods only then. My friend and I only had Goonmod and Pocohud installed. I posted this here as a Just In Case thing. I didn't know which one it'd be.

**Comment by thatguyfrombb** [comment]
Most likely, yes. Although BLT could still crash on some update, but I don't think we'll see that in PD2. Maybe when they release it for linux too they'll change too much of it, but I doubt it.

**Comment by SirWaddles** [comment]
dis p dumb yo
