### ISSUE TITLE
BLT not showing up ingame

### ISSUE THREAD

**Issue by Hotkeq** [JamesWilko/Payday-2-BLT#183]
BLT isn't showing up ingame, the upto date mod button and the mod options don't show even when no mods are in the folder, like its not hooking or something, i've tried everything i can think of, reinstalling the c++ package, re-downloading the IPHLPAPI.dll and mods folder and running the exe in different compatibility modes. Nothing works, currently on windows 10 64bit

my folders
https://gyazo.com/da4319f926e42276774744c043e6cae4

**Comment by AlphaDelta9** [comment]
Enable fullscreen optimization on payday2_win32_release

**Comment by Hotkeq** [comment]
Perfect 😄 , Working fine now
