### ISSUE TITLE
A space in mod identifier can block the update of other mods

### ISSUE THREAD

**Issue by TdlQ** [JamesWilko/Payday-2-BLT#21]
An mod identifier containing a space will prevent the update of all the mods after it.
A friend had the problem with [this mod](http://forums.lastbullet.net/mydownloads.php?action=view_down&did=12976) (unregistered?).

A simple fix can be:
```lua
function LuaModUpdates:FetchUpdatesFromAPI( path, callback )
	path = path:gsub(" ", "%%20")
	dohttpreq( path, function( data, id )
```

**Comment by JamesWilko** [comment]
Fixed in yesterdays updates. Parts that appear in mod identifiers will now be escaped for the URL.
