### ISSUE TITLE
Reserved word "type" used as a parameter

### ISSUE THREAD

**Issue by TdlQ** [JamesWilko/Payday-2-BLT#22]
The function LNetwork:SendToPeersExcept() can't work as is.

This works:
function LNetwork:SendToPeersExcept(peer, type_prm, data)
[followed by according replacements]

**Comment by SirWaddles** [comment]
I added a pull request to fix this, when it's simple stuff like this it'd probably take less time to write an issue than it would to fix it and PR.

**Comment by SirWaddles** [comment]
Pull Request submitted and merged. Issue resolved.
