### ISSUE TITLE
Suggestion: Allow Keybindings to Overlap

### ISSUE THREAD

**Issue by Spackster** [JamesWilko/Payday-2-BLT#24]
I think it would be a good idea to add in an option for keybindings in the specific mod's menu and mod keybinds menu in case we want a script to be activated with [F] along with using [F] for shout/interact.

**Comment by SirWaddles** [comment]
Reminds of when you have too many mods in Minecraft and you -run out- of keyboard buttons to assign things to, and no-one wants to make a unifying UI interface for mod actions.

**Comment by SpackyBae** [comment]
Yeah, I can remember installing a mod pack, and wonder what to re-config most of the keys to.

**Comment by JamesWilko** [comment]
Payday 2 does not allow overlapping keybinds, so will not implement.
