### ISSUE TITLE
NetworkGame hooks are not working

### ISSUE THREAD

**Issue by Lordmau5** [JamesWilko/Payday-2-BLT#25]
I am desperately trying to get the NetworkGame hooks ("OnEnteredLobby", "OnGameJoined", ...) to work, but they are just not calling *anything*.

Not even when I put some debug prints into the "mods/base/lua/NetworkGame.lua" file - not even that get's logged to the console...

Did Overkill change some stuff up over here?

I could really get a hold of a method:
* Method that get's called once a client **loads** into a lobby (or in-game) for the **client-side**

Then I could trigger some variables from the server to the client over the *LuaNetworking* methods.

**Comment by polarathene** [comment]
Far as I know NetworkGame isn't used anymore, try search the codebase for where it might be made available? I'm sure I read somewhere on UC that Overkill has split NetworkGame into other classes, the methods you're wanting to change probably exist elsewhere, with similar code and method names.

I've been working with the network codebase quite a bit now, you're probably interested in either client/hostnetworksession and hoststateingame + hoststateinlobby :) Also networkmanager

**Comment by Lordmau5** [comment]
Recent updates after the Microtransaction-Crisis have fixed it, it seems to work again...
I've found a different approach though, I haven't updated this issue in a while :D
