### ISSUE TITLE
Crimefest update broke blt

### ISSUE THREAD

**Issue by aayanl** [JamesWilko/Payday-2-BLT#27]

**Comment by SirWaddles** [comment]
Yea, it was a pretty big update.

I'm at work today, so Wilko is having a look. We're hoping to have it fixed before the weekend.

Some more detail about the crash (is it even a crash?) would be helpful though.

**Comment by Faildozer** [comment]
Does not crash, it just does nothing.

01:07:27 AM Log: CURL INITD
01:07:27 AM Log: Initiating Hook
01:07:31 AM Log: CURL CLOSED

**Comment by SirWaddles** [comment]
I've got some basic stuff working, shouldn't be too long left.

**Comment by TheOfficialJosh** [comment]
Not to rush but how's the progress Waddles?

**Comment by SirWaddles** [comment]
We're still working on it. Came across a few snags as expected, getting through it all though.

**Comment by SirWaddles** [comment]
Okay, new version of BLT's been released. Seems to be working okay.

Small note for devs:
The pcall protection's no longer in place, we had some trouble reimplementing this one. I've got a seperate binary with it working, but I'm not sure how stable it will be. I'll post it as an alternate release if people still want it.

(This was the feature that allowed error reporting in post/pre hooks)
