### ISSUE TITLE
Error Reporting

### ISSUE THREAD

**Issue by Kyle873** [JamesWilko/Payday-2-BLT#30]
So, maybe I'm just missing something extremely obvious here, but it seems to me that BLT does absolutely no error reporting whatsoever when it encounters Lua errors, it just stops dead in it's tracks.

This has made me waste a whole hell of a lot of hours trying to find stupid errors such as syntax goofs and mistyped functions. As someone who's jumping into PAYDAY 2 modding for the first time and reading/learning the Lua structure, this is an extremely huge barrier to entry IMO and should be addressed in some fashion.

In the vein hope to get some error reporting, I wrapped a lot of things in pcall() as I wrote them to help me find issues, but even that just seems to give me errors whenever it feels like it, doesn't seem to be any consistency to it whatsoever.

Hopefully I don't sound like I'm ragging on the hook too much, because besides that and another issue I will post later, the hook is great and is very stable and has a good API behind it.

Oh, and I should probably mention that this is all on the current release hook, working on Update 78 (since I refuse to touch anything past that for the moment)

**Comment by SirWaddles** [comment]
I'm not really sure what you're talking about.

BLT (Specifically vanilla BLT, not Club Sandwich Edition) will report any lua errors to both the developer console, and with timestampped entries in the mods/logs folder reporting exactly what the problem is.

We even hooked some of PAYDAY's calling mechanisms to try and be more friendly to developers, so that anything hooked in the post-loads or pre-loads will be reported as well.

**Comment by Kyle873** [comment]
Oh, that's probably it right there then. I'm using CSE in order to use both HoxHud and lua stuff at the same time. If this is true then I guess I'm stuffed then.

**Comment by SirWaddles** [comment]
Olipro might be able to do something similar if you make an issue over at its repo.

[https://github.com/Olipro/Payday-2-BLT_Club-Sandwich-Edition](Club Sandwich Edition Repository)

**Comment by SirWaddles** [comment]
Oh wait. Sorry. Yea, I just looked into it briefly. CSE used to be the same. He intentionally removed this functonality, citing it encourages bad development.

[Commit here](https://github.com/Olipro/Payday-2-BLT_Club-Sandwich-Edition/commit/069a04659e1c99ccff709d27ebbe79a863aa96e9)
