### ISSUE TITLE
Crash issue related to PocoHud

### ISSUE THREAD

**Issue by Malidictus** [JamesWilko/Payday-2-BLT#31]
I know this isn't BLT-specific, but I'm listing it for completeness' sake. Crashed out of nowhere. Got the following crash report:

---
Application has crashed: C++ exception
mods/PocoHud3/poco/Hud3.lua:150: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.41.6
	CPU : Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 780 / nvd3dum.dll[10.18.13.5560]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     416321    0MB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : CREATIVE (Speakers (Sound Blaster Audigy Fx))
---

What's in there is a simple function that I'm not really clear on the... Function of:

function TPocoHud3:AddDmgPopByUnit(sender,unit,offset,damage,death,head,dmgType)
	if unit and alive(unit) then
		local isPlayer = unit:base().upgrade_value
		if not isPlayer then -- this filters PlayerDrama related events out when hosting a game
			self:AddDmgPop(sender,self:_pos(unit),unit,offset,damage,death,head,dmgType)
		end
	end
end

**Comment by SirWaddles** [comment]
Yea, I'm guessing this is to do with the crimefest lua changes. PocoHUD will have to be updated.

**Comment by Malidictus** [comment]
I suck at text formatting on GitHub... Yeah, this is a Poco issue, and I've already posted it to PocoMods, as well. I'm just hoping it's something I can disable temporarily. Thank you for the reply :)

**Comment by TheOfficialJosh** [comment]
That's interesting because I'm running PocoHud without an issue on the newest version. Could there be a setting that's causing it?

**Comment by Malidictus** [comment]
We sort of tracked the issue down to the Aftershock truck, which I believe is what caused my own crash - another player attempted to drive it and crashed me out. Someone else reported seeing this with the Meltdown forklifts. Seems to be vehicle-related. My blind guess is Poco is attempting to parse vehicles as players and crashing when they don't have the necessary functions or some such. Poco's maker suggested a few temp fixes for the moment, specifically replacing:

local isPlayer = unit:base().upgrade_value

with:

local unitTweak = unit and alive(unit) and unit:base()._tweak_table

but others are reporting crashes in other places with this fix. I've not run vehicle-centric maps since then - I didn't think of it.

**Comment by JamesWilko** [comment]
This is a PocoHud issue, not a BLT issue. Report it on the [PocoHud GitHub](https://github.com/zenyr/PocoHud3) instead.
