### ISSUE TITLE
Error when leaving the Safehouse

### ISSUE THREAD

**Issue by cjur3** [JamesWilko/Payday-2-BLT#32]
mods/base/req/utils.lua:170: attempt to index a nil value

This is the message from the crashlog

**Comment by cjur3** [comment]
Just replace line 169 in base/req/utils.lua with:
	if managers and managers.trade and not alive( player ) and managers.network:session():local_peer():id() then

**Comment by aayanl** [comment]
I made a PR for cjur #33

**Comment by JamesWilko** [comment]
Merged and updated.
