### ISSUE TITLE
controller not working with gamepad

### ISSUE THREAD

**Issue by starnuts77** [JamesWilko/Payday-2-BLT#34]
For some reason the gamepad causes me to crash when entering the pre-game loadout screen, and when I remove the hook the game will still continue to crash until I uninstall it and reinstall it.  Please help
https://www.dropbox.com/s/fkmpqt8qusy1nhl/payday2_win32_release_2117156_crash_2015_10_27T19_30_26C0.mdmp?dl=0

**Comment by TheOfficialJosh** [comment]
Can you provide the crash.txt file in the Local Appdata Payday folder? Type this in windows explorer:
%localappdata%\PAYDAY 2

**Comment by starnuts77** [comment]
Application has crashed: C++ exception
[string "core/lib/managers/controller/corecontroller..."]:344: Invalid controller wrapper. Tried to connect to non-existing controller id "keyboard".

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      AcXtrnal  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     VirtualQuery                                        
                      kernel32  (???)     SetUnhandledExceptionFilter                         
                      kernel32  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      kernel32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlInitializeExceptionChain                         
         payday2_win32_release  (???)     ???      

I got it working but, I am not sure if it will continue to do so.  I have problems with Luffy's Holohud as well seems it has issues with controllers as well.


SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      AcXtrnal  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     VirtualQuery                                        
                      kernel32  (???)     SetUnhandledExceptionFilter                         
                      kernel32  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      kernel32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlInitializeExceptionChain                         
         payday2_win32_release  (???)     ???

**Comment by SirWaddles** [comment]
So the game doesn't launch with just base BLT installed?

Try leaving your keyboard plugged in, but then mapping stuff to the gamepad/controller in game.

**Comment by starnuts77** [comment]
No it works I just couldn't get into the pre-game loadout screen. It was very weird, it crashed once (see crash log above) then I had problems getting the base game to work. Kept crashing when joining the pre-game load out screen. I got it fixed by removing the save000 file from the userdata folder.
