### ISSUE TITLE
Game crahes wheni start it up.

### ISSUE THREAD

**Issue by JustDevin** [JamesWilko/Payday-2-BLT#36]
Crashes after all the into videos are done,when the Press any key to continue tries to load up the game crashes.

**Comment by SirWaddles** [comment]
Can you post your crash.txt, BLT log and binary sha1?

**Comment by Applejaxc** [comment]
I'm having the same issue. Reinstalled last night, game kept throwing access violation errors at me until I added the d39dxwhateverwhatever .dll fix. Now with BLT trying to run, I crash as soon the intro videos are done (can't see my character/main menu).

"Sat Oct 31 10:29:40 2015


Application has crashed: C++ exception
mods/Poser/PoserLua/MenuScene.lua:162: attempt to call method 'refresh' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlCreateHeap                                       
                         ntdll  (???)     RtlCreateHeap                                       
                         ntdll  (???)     NtQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ??? "

Yes I've installed (and reinstalled!) the proper C++

**Comment by SirWaddles** [comment]
Looks like an issue with Poser?

**Comment by Applejaxc** [comment]
Poser was the issue! How did you know? Is "Kernel" a handle Poser's creator uses or are you just familiar with what it tries to do?

Oh wait, no.

"Application has crashed: C++ exception
mods/Poser/PoserLua/MenuScene.lua:162: attempt to call method 'refresh' (a nil value)"

Sorry. I've been so annoyed by access violation errors since the start of crimefest I guess I gave up actually reading what my crashlogs said. Thank you, SirWaddles.
