### ISSUE TITLE
Crash in mid game

### ISSUE THREAD

**Issue by CurlySparkle** [JamesWilko/Payday-2-BLT#37]
Sometimes when playing Watchdogs or Alesso, the game will automactly crash for no reason, as i try looking for the problem of why is that happening, i found that the problem comes from the base folder, a lua called delayed_calls.lua, i dont if this also happen to some other people but this happen to me twice the amount when playing some random maps, i also try playing without mods and just leaving BLT alone and it still crashes randomly, this is the crash log.

Application has crashed: C++ exception
mods/base/req/delayed_calls.lua:23: attempt to call field 'functionCall' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.42.0
	CPU : Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 750 Ti / nvd3dum.dll[10.18.13.5598]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     48175    0MB
	OS : 6.1.7601 (Service Pack 1) 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Altavoces (USB Audio Device))

**Comment by xDiverGenTx** [comment]
Maybe some mods crash your game. I also have that problem too but when I delete a mod.... I cant remember the name of the mod, anyway the game isn't crash :-D

Maybe you should try to install single mod then test it.

**Comment by JamesWilko** [comment]
Delayed function calls are checked to ensure that this can not occur now.
