### ISSUE TITLE
Can't get Payday 2 BLT working again.

### ISSUE THREAD

**Issue by Jessemod93r** [JamesWilko/Payday-2-BLT#38]
I had BLT and a bunch of mods, like Pocohud. I tried installing Hox as well and it started crashing my game. So I removed it and my blt wasn't working. Now whenever I do the steps to install the BLT again it just flat out won't work. I'm not very good with computers and files and such, I was just following the internet's tutorials. What do I do now? I should probably also say that I validated the games files after I removed the mods folder and the IPHLPAPI. I still have the old mods folder. And whenever I try to go to the BLT website I cant get the download link from there. It just does the whole "about blank" thing or whatever. It's like EVERYTHING that could go wrong has

**Comment by xDiverGenTx** [comment]
Did you install Poser mod or Bullet... bullet something? (I cant remember its name) If yes, remove it. :-D

Or if you want to re-download the mod, here's the download link
http://paydaymods.com/download/

**Comment by Jessemod93r** [comment]
I installed Hoxhud. But the problem is that I removed my BLT and now I can’t reinstall it. All my mods and everything is gone, but when I try to start fresh it won’t work






Sent from Windows Mail





From: xDiverGenTx
Sent: ‎Saturday‎, ‎November‎ ‎14‎, ‎2015 ‎11‎:‎28‎ ‎AM
To: JamesWilko/Payday-2-BLT
Cc: Jessemod93r





Did you install Poser mod or Bullet... bullet something? (I cant remember its name) If yes, remove it. :-D

Or if you want to re-download the mod, here's the download link
http://paydaymods.com/download/

**Comment by xDiverGenTx** [comment]
HoxHUD is not compatible with BLT, Remove IPHLPAPI.dll file and try to reinstall it, Dont forget to use the newest version of BLT too! BLT:CSE is the version of BLT that compatible with HoxHUD still doesn't release the new version yet. So you can only BLT but NO HoxHUD or install HoxHUD but NO BLT.

**Comment by Jessemod93r** [comment]
I get that, I realized that as the problem. What’s happening is that whenever I try to re install BLT it still won’t work. And I’ve removed all my mods and everything






Sent from Windows Mail





From: xDiverGenTx
Sent: ‎Monday‎, ‎November‎ ‎16‎, ‎2015 ‎10‎:‎09‎ ‎AM
To: JamesWilko/Payday-2-BLT
Cc: Jessemod93r





HoxHUD is not compatible with BLT, Remove IPHLPAPI.dll file and try to reinstall it, Dont forget to use the newest version of BLT too! BLT:CSE is the version of BLT that compatible with HoxHUD still doesn't release the new version yet. So you can only BLT but NO HoxHUD or install HoxHUD but NO BLT.

**Comment by SirWaddles** [comment]
Try verifying integrity or even re-installing Payday. There were a few guides out and about after Crimefest came out that would break all subsequent BLT installations and it required a fresh re-install to be sorted out.

**Comment by xDiverGenTx** [comment]
Oh, I forgot about verify integrity of game cache. XD

**Comment by Jessemod93r** [comment]
I’ve already verified the cache. I guess my only option left it so reinstall the game. Will I lose my save? Or can I back it up somehow? And what about my Non-BLT mods?






Sent from Windows Mail





From: xDiverGenTx
Sent: ‎Monday‎, ‎November‎ ‎16‎, ‎2015 ‎10‎:‎39‎ ‎PM
To: JamesWilko/Payday-2-BLT
Cc: Jessemod93r




Oh, I forgot about verify integrity of game cache. XD

**Comment by xDiverGenTx** [comment]
re-install won't effect your game save.

Non-BLT mod... mod_override? Yes, mod_override still working even due the game update. Because mod_override is the kind of mod that will only replace the in-game texture only. (not  gameplay changing like BLT)

**Comment by GreatBigBushyBeard** [comment]
A good start would be to ensure that you have the dependencies installed.

**Comment by Jessemod93r** [comment]
Dependencies? 






Sent from Windows Mail





From: xDiverGenTx
Sent: ‎Tuesday‎, ‎November‎ ‎17‎, ‎2015 ‎9‎:‎31‎ ‎AM
To: JamesWilko/Payday-2-BLT
Cc: Jessemod93r





re-install won't effect your game save.

Non-BLT mod... mod_override? Yes, mod_override still working even due the game update. Because mod_override is the kind of mod that will only replace the in-game texture only. (not gameplay changing like BLT)

**Comment by JamesWilko** [comment]
Issue was before LuaJIT update, no longer applicable.
