### ISSUE TITLE
Can't use keybinds/chat when using a controller

### ISSUE THREAD

**Issue by Flexo013** [JamesWilko/Payday-2-BLT#40]
The game completely crashes when using the keyboard, you can find a report here: https://www.reddit.com/r/paydaytheheist/comments/3ullrk/bug_since_the_crimenet_hack_teaser_game_crashes/

**Comment by JamesWilko** [comment]
Should be fixed in the latest update. If it still occurs then re-open this issue, and attach a crash log.
