### ISSUE TITLE
Require statement

### ISSUE THREAD

**Issue by polarathene** [JamesWilko/Payday-2-BLT#42]
I'm migrating a mod from pd2hook to BLT where many scripts `require` another one that isn't a class but more like a json object with a bit of logic. This doesn't seem to work though, whenever running a keybind script that uses any of the required scripts the game crashes. I've tested a simple one in a mods folder called `custom`, however nothing seems to work. I've tried the following:

`mods/custom/script`
`custom/script`
`script`
*each again but with the .lua extension suggested by someone else*

There is no documentation on this type of statement with the BLT docs. It works perfectly with pd2hook and is a native lua feature, so I'm not sure what I'm doing wrong.

**Comment by polarathene** [comment]
Example script for a keybind:

```Lua
local arrItems = require 'mods/custom/spiral_staircase'
 
function spawnArr()
  local pos = managers.player:player_unit():position()
 
  for i=1,#arrItems do
    local unit = World:spawn_unit( Idstring(arrItems[i].type.id), pos + arrItems[i].location, arrItems[i].rotation )
    if unit and unit:interaction() then
      unit:interaction():set_active(true, true)
    end
  end
end
 
spawnArr()
```

Required script:
```Lua
local gold = {
  id = "units/payday2/pickups/gen_pku_gold/gen_pku_gold",
  dimensions = Vector3(34, 60, 17)
}
 
local arrItems = {
  {
  location = Vector3(30,0,0),
  rotation = Rotation(0,0,-0),
  type = gold
  }
  --And so on, too many chars to post on reddit
}
 
return arrItems
```

**Comment by VADemon** [comment]
> another one that isn't a class but more like a json object with a bit of logic.

That is a perfectly normal Lua file that will return the `arrItems` table and assign it to the `arrItems` variable. In fact you can embed this file into the example script code:

```lua
local arrItems = {
  location = Vector3(30,0,0),
  rotation = Rotation(0,0,-0),
  type = gold = {
	id = "units/payday2/pickups/gen_pku_gold/gen_pku_gold",
	dimensions = Vector3(34, 60, 17)
	}
  }
  --And so on, about 2k lines
}


function spawnArr()
  local pos = managers.player:player_unit():position()

  for i=1,#arrItems do
    local unit = World:spawn_unit( Idstring(arrItems[i].type.id), pos + arrItems[i].location, arrItems[i].rotation )
    if unit and unit:interaction() then
      unit:interaction():set_active(true, true)
    end
  end
end

spawnArr()
```

You can probably replace the `require` with `dofile` which should work just the same. Or try to require an empty existing file to see if the function itself is bugged.

**Comment by polarathene** [comment]
The function isn't bugged, had it requiring and working just fine with pd2hook. I was never able to get a working `require` going, even with something simple.

I'm aware I could embed, but it was a large file that was mostly data, the function itself was to use multiple of those data based lua files that I was writing via python scripts. Making a change to that function should be done via a single file, not requiring me to alter all duplicates of the function if it were embedded in each one.

I got around the issue some time ago by wrapping the data lua files as classes(persist) for keybinds to call.
