### ISSUE TITLE
Keybinds not working

### ISSUE THREAD

**Issue by polarathene** [JamesWilko/Payday-2-BLT#44]
I've set up a basic keybind script following the documentation here: http://payday-2-blt-docs.readthedocs.org/en/latest/mods/definition/ . When I run the game and go to Mods Keybinds I see my keybind prefixed with `Error:`, the same applies to the description. I click the keybind to set a key and get a warning `ERROR, Key "mouse 0" is already mapped to "Fire Weapon". please remap it first`. I'm not even given a chance to wait for input and provide a key,I can also hover over it and press enter and it sets enter. I have all other mods disabled and restarted, no idea why this is happening.

mod.txt:
```JSON
{
  "name": "Get My Peer ID",
  "description": "Prints local peer id to console via keybind.",
  "author": "Polarathene",
  "contact": "no@support.com",
  "version": "1.0",
  "updates": [
    {
      "revision": 1,
      "identifier": "bkin_getid"
    }
  ],
  "keybinds": [
    {
      "keybind_id": "bkin_getid-1",
      "name": "Print Peer ID to Console",
      "description": "Prints local peer id to console via keybind.",
      "script_path": "getid.lua",
      "run_in_menu": true,
      "run_in_game": true
    }
  ]
}
```

getid.lua:
```Lua
local me = managers.network:session():local_peer()
log("My Peer ID is: " .. tostring(me:id()) .. ", and my name is: " .. tostring(me:name()) .. "\n")
```

**Comment by goontest** [comment]
try adding the following to the mod.txt to fix the error prefix
"localized": false
try holding the left mouse button and pressing the key you want to assign to the option

**Comment by polarathene** [comment]
@goontest Your suggestion for setting the `localized` key works at preventing the `ERROR:` prefixes. @JamesWilko Why is this key not treated as false when not set?

@goontest The hold left mouse button advise works at setting a keybind, thanks.
@JamesWilko This is bad UX and it's not clear that you must set keybinds in this manner via the docs(if at all) or the UI screen for setting keybinds. If possible trigger input after a click and make a prompt for the user to press the key they wish to bind to.

The keybind provided here seems to run in menu but when using it in briefing screen of a lobby nothing happens in the console, both `run_in_menu` and `run_in_game` are set to true as you can see. I've replaced the code to run with just `log("test")` and now nothing prints to console or is written to the log txt file in `mods\logs\`, would seem the `log()` function is broken?

**Comment by JamesWilko** [comment]
You are assuming that it is intentional that binding a key attempts to use the mouse button as the bind target. This was a glitch due to updates to the key binding system introduced in Update 91, see https://github.com/JamesWilko/Payday-2-BLT/issues/41 for more information.

As keybinds are presented in the game using the menu system, they are localized by default like the rest of the menu system. Localized should be explicitly false if you do not wish to use a localization file.
