### ISSUE TITLE
Issue when download BLT in-game

### ISSUE THREAD

**Issue by pepe1987** [JamesWilko/Payday-2-BLT#46]
After finished the download of the new BLT version (BLT 1.06) and restart the game I have a crash to Desktop, the crash.log file point to this line
`mods/base/req/localization.lua:10: bad argument #1 to 'pairs' (table expected, got no value)`

I have no more data since I delete the folder and download the release from here.

Mods Installed:
Lobby layer Info
PocoHud
Reconnect to server
Driver's neck brace removed

**Comment by JamesWilko** [comment]
Issue was before LuaJIT update, no longer applicable.
