### ISSUE TITLE
Error in Keybind menu

### ISSUE THREAD

**Issue by rakion99** [JamesWilko/Payday-2-BLT#5]
i have a problem when i go to options > mod keybinds says in every key bind ERROR: mykeybindname any idea why? but i can still click the ERROR: mykeybindname and put a key and the script can run there no errors in the log, also the keybind description isnt showing if i remove the description the error is still appearing.
Here a image of the error:
![blterror](https://cloud.githubusercontent.com/assets/1360084/6995326/b0bf0044-dafd-11e4-8c86-cb42ae8a48e7.png)
this is my keybind code:
"keybinds" : [
        {
            "keybind_id" : "keybind_testmod01",
            "name" : "Custom Menu",
            "description" : "Opens the Custom menu",
            "script_path" : "Lua/Menu.lua",
            "run_in_menu" : true,
            "run_in_game" : true,
        }

**Comment by rakion99** [comment]
well i fixed it just adding
"localized" : false
but still the description isnt showing

**Comment by JamesWilko** [comment]
Descriptions for keybinds will now display as of the latest changes and update. Titles and descriptions will share the localized key when displaying the title or description.
