### ISSUE TITLE
Ignore update check on launch feature doesn't work.

### ISSUE THREAD

**Issue by epilimic** [JamesWilko/Payday-2-BLT#51]
Title pretty much says it all. If I go to the update manager then un-check one of my mods that I don't want to check for an update every time, it still checks for it and prompts me every time to update.

**Comment by xDiverGenTx** [comment]
So why don't you just update it?

**Comment by epilimic** [comment]
Because I customized it and don't want to. My choice of wanting to update a mod is irrelevant to this feature being broken.

**Comment by JamesWilko** [comment]
Ignore is only meant to suppress the current notification, not ignore the update. Update your mods, or you'll end up with problems further down the line.
