### ISSUE TITLE
Game crashing while using BTL and Dualshock 4

### ISSUE THREAD

**Issue by Bradizhkee** [JamesWilko/Payday-2-BLT#52]
I'm using sony dualshock 4 controller with ds4tool to play Payday 2. But when i install BTL game start crashing when loading the heist. I have tried to delete save000.sav in userdata folder -  no luck...

Maybe, the problem is in microsoft visual c++ file which is reqired to instal both on BLT and ds4tool?

**Comment by SirWaddles** [comment]
Can you show your Payday crash file after the error occurs?
(Usually at C:\Users\<YourName>\AppData\Local\PAYDAY 2)
Thanks

**Comment by Bradizhkee** [comment]
it was actually solved by reseting controls settings. 
P.S. i don't have crash file in that directory?
