### ISSUE TITLE
Game crashing when posting certain strings to in-game chat

### ISSUE THREAD

**Issue by PenguinOfLight** [JamesWilko/Payday-2-BLT#61]
Any time I post a message in the lobby or in-game containing a Percentage Sign ('%') followed by a **single digit integer**, the game crashes to the desktop. This was tested with no mods enabled aside from Payday 2 BLT, in order to ensure that BLT was at fault, as well as without BLT installed at all. In the first case, the game crashes when posting messages to chat, while in the second, the message is sent successfully and the game does not crash.

The [crash.txt](https://github.com/JamesWilko/Payday-2-BLT/files/439884/crash.txt) and [crashlog.txt](https://github.com/JamesWilko/Payday-2-BLT/files/439885/crashlog.txt) (which includes large amounts of data from other crashes) from one of my tests are available for your review.

I am unsure if this is capable of crashing other clients as well, or if it is restricted to the player. 

It may be an issue with the game attempting to parse % as the modulo operator.

**Comment by PenguinOfLight** [comment]
Update: players who do NOT have BLT can crash players who do by sending messages. This is a serious issue and could be easily used for griefing.

**Comment by RomanHargrave** [comment]
@PenguinOfLight my guess without looking at code is that it's being treated as a format string, or something. Not terribly familiar with the workings of the LUA base for BLT.

**Comment by SirWaddles** [comment]
It's just being [passed to gsub](https://github.com/JamesWilko/Payday-2-BLT-Lua/blob/master/mods/base/req/network.lua#L138), I don't get why lua searches the _subject_ of replacement for captures.

Also, keep in mind that this is an issue with the BLT Lua, and should probably be over in that repository.

**Comment by fanthos** [comment]
http://lua-users.org/wiki/StringLibraryTutorial
string.gsub(s, pattern, replace) searches any regex "pattern" in s and replace them with new regex "replace".
I think use "string.format" or ".." instead is a option.
