### ISSUE TITLE
BLT mods not receiving automatic updates 

### ISSUE THREAD

**Issue by Afbg123** [JamesWilko/Payday-2-BLT#62]
I've only recently come across this problem, and I've been struggling to find any solutions, as no one else seems to be having the same issues. Basically, none of the BLT mods I have installed (Newbies go back to overkill, Goonmod, Better Bots) have been auto-updating. It was never an issue in the past, I always received automatic updates from them when I went to the main menu, but as of late, none of the mods that are capable of receiving automatic updates have been able to do so. When I try to click update from the mod menu, the BLT console reads:

Launching Async HTTP Thread
[Error] Could not connect to PaydayMods.com API!

I've tried uninstalling and reinstalling BLT, verifying game cache, uninstalling individual mods, but I'm still getting the same results. Can anyone help with this issue?

**Comment by SirWaddles** [comment]
Hi there. Looks like I borkered it. Thanks for letting me know. I'll get back to you

**Comment by SirWaddles** [comment]
Oh, looks to be working okay for me.

Would you be able to let me know what happens if you just [visit this link?](http://api.paydaymods.com/updates/retrieve/?mod[0]=goonmod)

**Comment by Afbg123** [comment]
It links me to a webpage that says:

{"goonmod":{"name":"GoonMod","date":"2016-08-13 17:13:45","author":"Wilko","revision":"31","revision_id":"2585"}}

**Comment by SirWaddles** [comment]
Would you be able to log the request in BLT? See what it's trying to access?

There's no reason for it not to be working.

**Comment by Afbg123** [comment]
How do I do that?

**Comment by SirWaddles** [comment]
In [mods/base/req/update_mods.lua, at line 91](https://github.com/JamesWilko/Payday-2-BLT-Lua/blob/master/mods/base/req/update_mods.lua#L91) add some code just saying
log("Attempted Update URL: " .. url)

**Comment by Afbg123** [comment]
Ok, so some of the files in mods/base that I have didn't match the files from [Payday-2-BLT-Lua](https://github.com/JamesWilko/Payday-2-BLT-Lua). The BLT files and IPHLPAPI.dll I had were the ones downloaded from here: https://github.com/JamesWilko/Payday-2-BLT/releases/tag/1.07. 

When I try to use the files from the BLT LUA master, no mods except Goonmod work. I've tried using the IPHLPAPI.dll from different versions, and none of them work. So I think I've got the wrong combination of files, but I don't know which ones I should be using, because the only version of BLT that's working for me is this one https://github.com/JamesWilko/Payday-2-BLT/releases/tag/1.07

Here's the full log that comes through the console when I try to click to update any mod:

04:59:41 PM Log: Incoming HTTP Request/Request
04:59:41 PM Log: http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt&mod[1]=payday2bltdll&mod[2]=delayedcallsfix&mod[3]=goonmod&mod[4]=goonmodwepcust&mod[5]=phoenix&mod[6]=additionalpocohudtrackers&mod[7]=ICAPS&mod[8]=ONMS&mod[9]=pocohud3&mod[10]=poser&mod[11]=SDJBL&mod[12]=SPLS&mod[13]=NGBTO&mod[14]=LPI&mod[15]=BB&mod[16]=crosshaircustom&mod[17]=MWS&mod[18]=uHUDVanilla&mod[19]=DDI&mod[20]=nervINV&mod[21]=VCI
04:59:41 PM Log: 794
04:59:41 PM Log: Launching Async HTTP Thread
04:59:54 PM Lua: [Error] Could not connect to PaydayMods.com API!

**Comment by JamesWilko** [comment]
Use the download from the [website](http://paydaymods.com/download/), which is 1.07. Then update when prompted by the game. Do not use the github versions unless you know what you are doing, because they are developer versions.

**Comment by Afbg123** [comment]
That's the problem I'm having, I had the latest version that's available, the link on the paydaymods.com site links is the same download for the version that I was using (Payday2BLT_r11_r5.zip). The problem is I don't get any prompts to update BLT or any BLT mods when I go in game.

**Comment by SirWaddles** [comment]
I'm not really sure, both BLT and the Paydaymods API are working fine.

Do you have any firewalls in place that might be blocking the dll from accessing the internet?

**Comment by Afbg123** [comment]
I tried completely turning off my firewall, but it didn't have any result.
Resetting the firewall options didn't work either. I really have no idea
what could be causing this, as automatic updates were working fine up until
about a month ago. If it is a firewall problem, what settings should I
change?

**Comment by fanthos** [comment]
http://download.paydaymods.com/download/latest/payday2bltdll
http://download.paydaymods.com/download/latest/payday2blt
Download these two files, unzip and replace your file and try again.

**Comment by Afbg123** [comment]
Downloaded, updates still not working

**Comment by fanthos** [comment]
Can you join game hosted by others?

**Comment by Afbg123** [comment]
Everything is working completely fine, except automatic updates for BLT mods and trying to force download mod updates.
