### ISSUE TITLE
Suggestion: Update All Button

### ISSUE THREAD

**Issue by 47Haven** [JamesWilko/Payday-2-BLT#65]
So i've been using BLT since it was launched the first time, and in time, i have downloaded around 100+ BLT mods, with 83 mods currently in use. With every update, most of the mods i have will also need to be updated as well, and since i have tons of mods, sometimes there's a lot of mods that needs to be updated at the same time.

Now the problem is, when you have a lot of mods, and you can't see the list of the mods needed to be updated unless you go back to main screen, i need to check each mods for updates by clicking the update button. It's sometimes taxing when you get like 10-15 updates at once, and have to scroll each and every one of the mods to find the one that needs updating. So with that, can we get an update all button that checks every mods for update and update it on it's own?

I know it's a rather petty request, but if it's not much of a trouble, can it be done?

**Comment by SirWaddles** [comment]
Hi, this is more relevant to the [Lua Interface](https://github.com/JamesWilko/Payday-2-BLT-Lua) as opposed to the hook itself.
