### ISSUE TITLE
download page timeout

### ISSUE THREAD

**Issue by Dillon-Milo-Babb** [JamesWilko/Payday-2-BLT#66]
I wanted to get BLT to load in HUDs, but every time I try to download it the page times out.

**Comment by JamesWilko** [comment]
Please post the download link you are trying to use, or the name of the mod you are trying to update. Otherwise we cannot look into this.

**Comment by Dillon-Milo-Babb** [comment]
I just tried it again and it works now.  It was the download link for BLT, but it work now so yay.
