### ISSUE TITLE
creash by starting the game

### ISSUE THREAD

**Issue by mcproprot** [JamesWilko/Payday-2-BLT#70]
Sun May 14 10:55:19 2017

Application has crashed: C++ exception
mods/base/req/json-0.9.lua:372: Unexpected character at Line 1 character 1: 

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.70.234
	CPU : Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : Intel(R) HD Graphics 4600 / igdumdim32.dll[20.19.15.4531]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     24437MB 956KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Lautsprecher (G510s Gaming Keyboard))

**Comment by ZataraTMM** [comment]
Try deleting your saves folder, or put it on your desktop and see if it works.
