### ISSUE TITLE
PAS: Desync Update

### ISSUE THREAD

**Issue by stevefan1999** [JamesWilko/Payday-2-BLT#73]
breaking changes are made by OVK

update the hook ASAP

**Comment by ZataraTMM** [comment]
Why don't you try updating it ASAP and see how it works ?

**Comment by BangL** [comment]
Patience is a virtue

**Comment by james-wilkinson-sb** [comment]
LuaJIT was not launched with the desync beta update. If there is a specific crash related to the BLT, then post that or you will be ignored.

**Comment by JamesWilko** [comment]
LuaJIT was not launched with the desync beta update. If there is a specific crash related to the BLT, then post that or you will be ignored.
