### ISSUE TITLE
Not Working Anymore

### ISSUE THREAD

**Issue by greatguy25** [JamesWilko/Payday-2-BLT#75]
BLT isn't working anymore in Payday 2.

**Comment by Luffyyy** [comment]
It doe,s you probably downloaded it through the website which is outdated atm..
get the latest here: https://github.com/JamesWilko/Payday-2-BLT/releases

**Comment by TheRealKiller** [comment]
Thanks! It works for me now.

**Comment by greatguy25** [comment]
Thanks!
