### ISSUE TITLE
Issues after using multiple scripts

### ISSUE THREAD

**Issue by TheDentistPD** [JamesWilko/Payday-2-BLT#8]
Hi,

There is a bug that ruins the easy drag & drop way of using scripts. After a certain amount of scripts, some of them don't work properly anymore. For example, after about 15 seperated scripts, the character blocker script didn't work correctly anymore. It stopped working on clients, only bots were affected. The way of solving the problem was merging multiple mods into an extra folder until I had 15 seperated folders left, so dragging & dropping into the mods folder is not working for me anymore. The script itself works fine if the amount of seperate scripts is below the threshold. Basically, the steps to reproduce the problem are to get over 15 seperate scripts with the character blocker script installed. I guess that there are other scripts that are affected too. You can find the script here: http://www.mediafire.com/download/n15p9dn4wzl9bl0/Character+Blocker+BLT.zip
![scriptmenu](https://cloud.githubusercontent.com/assets/11388484/7070329/8f3c04fa-dede-11e4-93f0-8c6033d4dc25.png)

**Comment by JamesWilko** [comment]
Non-reproducible with standard scripts.
