### ISSUE TITLE
(PRBLM) PAYDAY 2 doesnt start/launch with BLT.

### ISSUE THREAD

**Issue by Guest173661** [JamesWilko/Payday-2-BLT#83]
After 3 days of usage until today. no longer works. Already installed that Microsoft c++ thing for the mod loader to work. Made it to run on Admin mode, Still a no. I have installed 10 mods, [Long list ahead.]

- WolfHUD
- Reconnect to server
- Chat Commands + RTD
- Better Bots
- Cook Off Blur removal
- Slider Values
- {ABTCTB (Ask Bot to Carry the Bag)       }
- {ABTFTD (Ask Bot to Fix the Drill)           } (Yes, Its all about Bots.)               
- {ITER (A mod that fixes AI navigations.) }
- Inventory Right-Click menu (or what I call: Quick-Inventory Menus)

[EDIT]: I got it from GitHub (THIS.), Latest. :[EDIT]

**Comment by TimLS** [comment]
I am assuming you downloaded the latest release of BLT from https://github.com/JamesWilko/Payday-2-BLT/releases (1.08)? If so, I suggest you do that first and then run PayDay 2 with only BLT to see if it works. I don't understand how BLT is the problem as I am using BLT 1.08. Lastly, I would recommend only playing with one mod at a time to determine which one is causing the problem.

P.S. I read that you said you got the GitHub version, but I said it anyways in the event you may have downloaded an alternative version.

Good luck.

**Comment by Guest173661** [comment]
Ok, It works fine. but it crashes sometimes after completing a heist.
