### ISSUE TITLE
BLT causes crash (more in description)

### ISSUE THREAD

**Issue by adityajaypal** [JamesWilko/Payday-2-BLT#87]
After the latest update, the game would start with all the loading videos (even though I had the mod to skip them installed) and would then crash when I pressed any button to continue. I tried playing with the mods and BLT removed to the same effect.

I only have weapon mods installed.

I tried 2.0 and now the game would open to a cmd prompt, then to a black screen and then would CTD.

Any help?

Edit: Updated BLT and fixed the problem!

**Comment by ELYARL** [comment]
NO MODS NEW BLT
Fri Sep 01 03:22:46 2017


Application has crashed: C++ exception
[string "lib/managers/missionmanager.lua"]:288: attempt to call method 'client_on_executed' (a nil value)



SCRIPT STACK

lib/network/handlers/unitnetworkhandler.lua:558


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.315.
	CPU : AMD Athlon(tm) X4 840 Quad Core Processor (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 11.0 
	GPU : NVIDIA GeForce GT 730 / nvd3dum.dll[22.21.13.8541]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8135MB 504KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Динамики (Realtek High Definition Audio))

**Comment by JamesWilko** [comment]
Fixed in https://github.com/JamesWilko/Payday-2-BLT-Lua/commit/1c85114868dabef452ee3a709f1d895c141200e8.
