### ISSUE TITLE
Crash after joining someone's lobby (new blt)

### ISSUE THREAD

**Issue by fvinsensius** [JamesWilko/Payday-2-BLT#89]
Application has crashed: C++ exception
[string "lib/managers/missionmanager.lua"]:288: attempt to call method 'client_on_executed' (a nil value)

SCRIPT STACK

lib/network/handlers/unitnetworkhandler.lua:558

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.315.
	CPU : Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce 930MX / nvldumd.dll[22.21.13.8541]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     3979MB 28KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Conexant (Speakers (Conexant SmartAudio HD))

**Comment by GreenGhost21** [comment]
Getting an identical crash here as well.

**Comment by FrostFire25699** [comment]
I am getting the same crash here.

**Comment by PhantomGamers** [comment]
I'm getting the same issue, however sometimes it references this line instead:
lib/network/handlers/unitnetworkhandler.lua:568

**Comment by PhantomGamers** [comment]
A temporary fix is to delete the "base" folder and use the base folder from the 1.08 release, works fine for now, but it won't work with mods updated with the new mod.txt so use the old mods for now. Credit to "Respect Wamen" on the Steam forums for figuring it out: http://steamcommunity.com/app/218620/discussions/8/1474221865186057356/

**Comment by offyerrocker** [comment]
This happens to me too, with a fresh install of BLT and no other mods or lingering mod files. Hosting seems to work alright, though.

**Comment by ProvoloneCheese** [comment]
Ok so far I have 49 mins in without a crash.      
This version of wolfhud: https://steamcommunity.com/linkfilter/?url=https://cdn.discordapp.com/attachments/198281587404570624/353042120312881153/WolfHUD.zip

Download BLT version 2.0 AND 1.08 install 2.0 normally but delete and replace the base folder with the one from 1.08

BLT Downloads: https://github.com/JamesWilko/Payday-2-BLT/releases

Thanks for the help guys I did not come up with this fix; I got info for it from this thread... http://steamcommunity.com/app/218620/discussions/8/1474221865186057356/
Hope this fixes it for you guys to.

**Comment by fvinsensius** [comment]
fixed in BLT 2.1 thanks
