### ISSUE TITLE
Game needs restart after finishing a heist/leaving a lobby

### ISSUE THREAD

**Issue by alpha1812** [JamesWilko/Payday-2-BLT#9]
After completing a heist and leaving the lobby, crime.net is blank with no server availble to join.
Issue can sometimes occur after being kicked by the host or simply leaving the lobby
The following line can be found in logs:
FATAL ERROR: [string "lib/network/base/networkpeer.lua"]:959: attempt to index a nil value
The line is repeated until the game is closed
mods used: Pocohud, Goonmod

**Comment by JamesWilko** [comment]
This was an issue with a change introduced in GoonMod, it's been fixed as of the latest patch.
