### ISSUE TITLE
[Bug] No Mod settings during a game

### ISSUE THREAD

**Issue by wezu123** [JamesWilko/Payday-2-BLT#91]
I've tried to set my WolfHud after BLT 2.0 Update during a heist, but there's not even any mod related tab in escape menu. Will it be fixed?

**Comment by segabl** [comment]
Can confirm this issue, the Mod Options menu node disappeared after update to the latest BLT update. Intended or an oversight?

**Comment by JamesWilko** [comment]
Added in JamesWilko/Payday-2-BLT-Lua@89240f9, will be live in next update.
